"""add billing tables

Revision ID: 0b5f5a90b90a
Revises: ed235fd85eca
Create Date: 2026-03-22 22:53:06.817956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b5f5a90b90a'
down_revision: Union[str, None] = 'ed235fd85eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('record_type', sa.String(), nullable=True))
    op.add_column('medical_records', sa.Column('next_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_records', 'next_date')
    op.drop_column('medical_records', 'record_type')
    # ### end Alembic commands ###
